services:
  postgres:
    image: postgres:16
    container_name: easysearch-postgres
    environment:
      POSTGRES_DB: easysearch
      POSTGRES_USER: easysearch
      POSTGRES_PASSWORD: easysearch
    ports:
      - "5432:5432"
    volumes:
      - easysearch_postgres_data:/var/lib/postgresql/data

  ozon-scraper:
    build: ./ozon-scraper
    container_name: easysearch-ozon-scraper
    ports:
      - "8000:8000"

  wildberries-scraper:
    build: ./wildberries-scraper
    container_name: easysearch-wildberries-scraper
    ports:
      - "8001:8001"
    shm_size: "1gb"

  yandexmarket-scraper:
    build: ./yandexmarket-scraper
    container_name: easysearch-yandexmarket-scraper
    ports:
      - "8002:8002"

volumes:
  easysearch_postgres_data: